spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/films
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

jwt:
  secret: secretKey
  expiration: 86400000  # 24h in millis

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
